# Generated by Django 4.2.19 on 2025-03-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="主题")),
                ("body", models.TextField(verbose_name="内容")),
                ("sender", models.EmailField(max_length=254, verbose_name="发件人")),
                ("recipient", models.EmailField(max_length=254, verbose_name="收件人")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
                (
                    "folder",
                    models.CharField(
                        choices=[("inbox", "收件箱"), ("sent", "已发送")],
                        default="inbox",
                        max_length=10,
                        verbose_name="文件夹",
                    ),
                ),
            ],
        ),
    ]
