# Generated by Django 4.2.19 on 2025-03-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="姓名")),
                ("email", models.EmailField(max_length=255, verbose_name="邮件地址")),
            ],
        ),
    ]
