# Generated by Django 4.2.19 on 2025-03-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_app", "0002_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否删除"),
        ),
        migrations.AddField(
            model_name="email",
            name="is_flagged",
            field=models.BooleanField(default=False, verbose_name="是否星标"),
        ),
    ]
