# Generated by Django 4.2.19 on 2025-03-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_app", "0003_email_is_deleted_email_is_flagged"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="姓名")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("gender", models.CharField(max_length=255, verbose_name="性别")),
                ("email", models.EmailField(max_length=255, verbose_name="邮件地址")),
                ("phone", models.CharField(max_length=255, verbose_name="电话号码")),
                ("address", models.CharField(max_length=255, verbose_name="地址")),
            ],
        ),
    ]
