# Generated by Django 4.2.19 on 2025-04-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_app", "0005_personalinfo_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personalinfo",
            name="user",
        ),
        migrations.AddField(
            model_name="email",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="email_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="attachment_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
