# Generated by Django 4.2.19 on 2025-04-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_app", "0006_remove_personalinfo_user_email_attachment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="email",
            name="attachment_name",
        ),
        migrations.AddField(
            model_name="email",
            name="attachment_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
