# Generated by Django 4.2.19 on 2025-04-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mail_app",
            "0007_remove_email_attachment_remove_email_attachment_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="address",
            field=models.CharField(max_length=255, verbose_name="城市"),
        ),
    ]
